version: '3.8'

services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      - HOME=/ollama
    volumes:
      - .volumes/.ollama:/ollama/.ollama
    group_add:
      - video
    ipc: host
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined

  open-webui:
    build:
      context: .
    args:
      OLLAMA_BASE_URL: '/ollama'
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./.volumes/.webui:/app/backend/data
    restart: always
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
    ports:
      - "3000:3000"
      - "3001:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=asdf'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped